name: CI

on: 
  push:
    branches:
      - develop/*

jobs:
  CI:
    permissions:
      contents: read
    runs-on: Ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Node
        uses: actions/setup-node@4
        with:
          node_version: 24
      - name: install dependency
        run: npm ci
      - name: format
        run: npm run format
      - name: test lint
        run: npm run lint
